FiBo-36: Add SVG export of Use Case Diagram
Cebox82/FiBo pull request #1
Opened 2022-10-23 16:07 UTC by jens1o

fixes https://dhbw-karlsruhe.myjetbrains.com/youtrack/issue/FiBo-36/Create-the-Overall-Use-Case-Diagram

2022-10-23 20:42 UTC, Jonas-Karl approved these changes

2022-10-24 06:25 UTC, XSnelliusX requested changes
The is not shown in the svg.

2022-10-24 06:26 UTC, jens1o commented
> The user is not shown in the svg.

Thanks for the hint! I updated the diagram to also include the user. I missed to check the box to also embed images when I have been exporting the UCD.

2022-10-24 06:28 UTC, XSnelliusX approved these changes
Nice looks good now

2022-10-24 06:54 UTC, merged