FiBo 70 add scan receipt activity diagram
Cebox82/FiBo pull request #17
Opened 2022-11-30 17:40 UTC by jens1o

2022-11-30 18:05 UTC, Jonas-Karl requested changes
should the order of docs/use_cases/UC_6_evaluate_scanning_receipts/Slice 3.png and docs/use_cases/UC_6_evaluate_scanning_receipts/Slice 4.png change? 
It looks like slice 4 should come before slice 3.

Anyways I added some comments to clarify everything a bit more. Maybe these comments result in changing a bit more - I did not check wether or not I am destroying the feature file with the comments when you simply commit them :D

2022-11-30 18:10 UTC, ChrisEwert commented on docs/use_cases/UC_6_evaluate_scanning_receipts/UC_6_evaluate_scanning_receipts.md
> +- date
The store can't be optional, right? It is the 'title' in our history

2022-12-02 12:50 UTC, Cebox82 commented on docs/use_cases/UC_6_evaluate_scanning_receipts/UC_6_evaluate_scanning_receipts.md
> +    Then I am on the "scanning receipt" form
Your change is also possible, I think. But when I did another narration, I saw some examples where you use the syntax When/Then "I am"

2022-12-02 14:50 UTC, Cebox82 approved these changes

2022-12-07 16:14 UTC, jens1o commented on docs/use_cases/UC_6_evaluate_scanning_receipts/UC_6_evaluate_scanning_receipts.md
> +- date
Thanks, I've reflected this.

2022-12-07 16:14 UTC, jens1o commented on docs/use_cases/UC_6_evaluate_scanning_receipts/UC_6_evaluate_scanning_receipts.md
> +    Then I am on the "scanning receipt" form
I opted to use a "When I take a picture of a receipt"

2022-12-07 17:32 UTC, merged