Fi bo 142 income change wording
Cebox82/FiBo pull request #46
Opened 2023-04-22 10:59 UTC by ChrisEwert

2023-04-22 18:08 UTC, jens1o requested changes
Works perfectly fine. This could however benefit from UI testing. :)

2023-05-02 15:47 UTC, jens1o commented
@XSnelliusX is working on a option to test this. If his efforts can't help, we'll merge it as-is.

2023-05-03 07:53 UTC, XSnelliusX commented
I could not find a way for the tests to work properly. Therefore this PR can be merged without Tests.

2023-05-03 07:53 UTC, XSnelliusX approved these changes

2023-05-03 07:54 UTC, jens1o approved these changes

2023-05-03 07:54 UTC, merged