add use case for manually adding of data #FiBo-47 work 3h
Cebox82/FiBo pull request #5
Opened 2022-11-02 19:56 UTC by XSnelliusX

2022-11-02 19:57 UTC, jens1o commented on docs/SRS.md
> +  alow to categorize and filter the displayed data.
```suggestion
  allow to categorize and filter the displayed data.
```

2022-11-02 19:58 UTC, jens1o commented on docs/SRS.md
> +
```suggestion
```

duplicate content

2022-11-02 19:59 UTC, jens1o commented on docs/SRS.md
> +respective deposited category and the price
As a follow-up ticket, we should create Use-Case Markdowns, where we can also embed the use-case diagram :)

2022-11-02 20:00 UTC, jens1o commented on docs/SRS.md
> +- 3.1.3 Manual adding of data
missing link to the markdown explaining that use-case :)

2022-11-02 20:00 UTC, jens1o commented on docs/use_cases/UC_4_manual_adding_of_data/UC_4_manual_adding_of_data.md
> +  i want to add a receipt by manually entering the data
```suggestion
  I want to add a receipt by manually entering the data
```

2022-11-02 20:01 UTC, jens1o commented on docs/use_cases/UC_4_manual_adding_of_data/UC_4_manual_adding_of_data.md
> +  in order to track my spend money.
```suggestion
  in order to track my spent money.
```

2022-11-02 20:01 UTC, jens1o requested changes
see comments :) great work overall!

2022-11-08 08:33 UTC, XSnelliusX commented
sollte alles gefixt sein

2022-11-08 16:44 UTC, jens1o approved these changes

2022-11-08 17:03 UTC, merged