FiBo-197 backend customise abstract user
Cebox82/FiBo pull request #71
Opened 2023-05-23 11:48 UTC by ChrisEwert

We changed the AbstractUser. It no longer uses username, first_name, last_name and is_staff. 
We removed every occurrence of a username and it instead uses email for everything. We changed the tests and the documentation too.

2023-05-24 15:12 UTC, Jonas-Karl requested changes
Looks good to me. I think the only thing that needs to be added are some tests for edge cases :)

2023-05-24 15:12 UTC, Jonas-Karl commented on docs/use_cases/UC_0_incomes_expenses/expenses_income.drawio.svg
What did you change here?

2023-05-24 15:12 UTC, Jonas-Karl commented on docs/use_cases/UC_3_change_added_data/change_added_data.drawio.svg
What did you change in this file?

2023-05-24 15:12 UTC, Jonas-Karl commented on backend/api/models.py
in this file, there are some untested lines of codes which. Could you add the according tests?

2023-05-24 15:14 UTC, Jonas-Karl commented
Does anybody know why the Android tests fail in this branch?

2023-05-25 08:09 UTC, ChrisEwert commented on backend/api/models.py
I have no idea, how to do that :D

2023-05-25 08:10 UTC, ChrisEwert commented on docs/use_cases/UC_0_incomes_expenses/expenses_income.drawio.svg
I removed every instance of "username". Even in the drawio.svg files. I guess somehow there was a username before? I dont know where

2023-05-25 08:17 UTC, XSnelliusX commented on .vscode/settings.json
This should not be on Git can you please add it to the gitignore?

2023-06-05 13:37 UTC, Jonas-Karl requested changes

2023-06-05 14:48 UTC, Jonas-Karl approved these changes

2023-06-05 15:57 UTC, Jonas-Karl commented on .vscode/settings.json
this file can be deleted / you can put it into gitignore

2023-06-05 18:48 UTC, jens1o approved these changes

2023-06-05 18:48 UTC, merged