FiBo-337: Add test plan
Cebox82/FiBo pull request #84
Opened 2023-06-01 09:11 UTC by jens1o

2023-06-01 09:44 UTC, jens1o commented
Todos:
1. remove names
2. remove `weglassen?` comments

2023-06-02 23:01 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +[TOC]
Add TOC here

2023-06-02 23:01 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +### 2. Evaluation Mission and Test Motivation (Chris)
Dont forget to remove the names in every headline

2023-06-02 23:01 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +(n/a) `weglassen?`
Here is the reason for n/a not given

2023-06-02 23:01 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +
See above mentioned comment

2023-06-02 23:01 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +| Designer | n/a | Identifies and defines the operations, attributes, and associations of the test classes. Responsibilities include: defines the test classes required to support testability requirem
Should we include any reasons?

2023-06-05 13:30 UTC, ChrisEwert requested changes
I noticed that sometimes people wrote "not applicable because ..." and other people wrote "(n/a because ...)". I think it should be consistent

2023-06-05 19:42 UTC, XSnelliusX requested changes

2023-06-05 19:42 UTC, XSnelliusX commented on docs/FiBo_RUP_Main_Test_Plan.md
> +![](https://pad.medialepfade.net/uploads/24f957c4-7f43-4cae-998e-08c653645b38.png)
These Pictures should be uploaded to Github. We should not use the mediapad links, because they may become invalid

2023-06-06 21:59 UTC, Jonas-Karl commented on docs/FiBo_RUP_Main_Test_Plan.md
> +10. If asked, please grant FiBo any permissions it needs
```suggestion
Third approach (Real Android Device):
1. Download the APK located at the following location [github](https://github.com/Cebox82/FiBo/tree/master/apk) 
2. Save the downloaded apk file to your android device (USB / Bluetooth / directly downloaded from github)
3. Install FiBo
    4. If the installation is possible you can feel free to test the FiBo app
    5. If the Installation is not possible you might need to adjust some settings
        5.1. Check if you've allowed the setting: [allow installation from unkown sources](https://www.maketecheasier.com/install-apps-from-unknown-sources-android/) in your android device 
        5.2 Click "See details" and then "Install anyways" if google play protect prevents an easy installation
6. If asked, please grant FiBo any permissions it needs
```

2023-06-10 14:31 UTC, jens1o commented
ping?

2023-06-11 09:02 UTC, XSnelliusX approved these changes
lgtm

2023-06-11 12:44 UTC, Jonas-Karl commented
Table of content is still missing

2023-06-11 13:48 UTC, ChrisEwert approved these changes

2023-06-11 14:41 UTC, merged